name: "mockoon-cli"
description: "Run Mockoon CLI as a GitHub Action"
branding:
  color: "white"
inputs:
  version:
    description: "Mockoon CLI version to pull from NPM"
    required: true
    default: "latest"
  data-file:
    description: "Mockoon CLI data file (local file or URL)"
    required: true
  port:
    description: "Mockoon CLI port"
    required: true
    default: "3000"
runs:
  using: "composite"
  steps:
    - name: "Run Mockoon CLI"
      shell: bash
      # keep --daemon-off to ensure compatiblity with <4.0.0
      # use & to run in background for >4.0.0
      run: |
        npm install -g @mockoon/cli@${{ inputs.version }}
        mockoon-cli start --daemon-off --data ${{ inputs.data-file }} --port ${{ inputs.port }} &
